/*
 * Question:
You are given a string s consisting only of letters 'a' and 'b'. In a single
step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some
characters of a given string without changing its order. Note that a subsequence
does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as
forward.

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/remove-palindromic-subsequences
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。
*/

#include <string>

namespace lc {

class Solution {
   public:
    int operator()(std::string s) { return removePalindromeSub(s); }

   private:
    int removePalindromeSub(std::string s) {
        int n = s.size();
        for (int i = 0; i < n / 2; ++i) {
            if (s[i] != s[n - 1 - i]) {
                return 2;
            }
        }
        return 1;
    }
};

}  // namespace lc